### ISSUE TITLE
Overcommit graph

### ISSUE THREAD

**Issue by blogh** [gleu/gnuplot_pgcluu#2]
I get  weird y axis labels for the attached data. Is this normal ?

gnuplot_pgcluu
![commit_memory](https://user-images.githubusercontent.com/16720048/211326389-574e4f92-0806-4d08-947b-152cf205cc10.png)

pgcluu
![commit_memory](https://user-images.githubusercontent.com/16720048/211326458-d141d7fc-f49b-46d7-9236-dfb2c3f839e7.png)

[commit_memory.csv](https://github.com/gleu/gnuplot_pgcluu/files/10373774/commit_memory.csv)

**Comment by gleu** [comment]
I thought the numbers were in unit of bytes. It may be kilobytes. I'll check right away.

**Comment by gleu** [comment]
OK, so pgcluu_collectd is doing something like this:

```
$ grep Commit /proc/meminfo 
CommitLimit:    43109864 kB
Committed_AS:   11285292 kB
```

And it just grabs the numbers. So it's definitely kilobytes. I'll fix this.

**Comment by gleu** [comment]
The fix is here: https://github.com/gleu/gnuplot_pgcluu/commit/7a5eb0e8c0fcc286ed32fc7a00158f952817ce1f

And here is the graph I get from your CSV file:

![commit_memory](https://user-images.githubusercontent.com/223410/212015089-a7b6a203-6d0e-465b-8ace-40c563d1afeb.png)

Thanks again.
